### ISSUE TITLE
为什么在 浏览器上的效果正常，在手机上字体变得很小。

### ISSUE THREAD

**Issue by hqwlkj** [omwteam/html2canvas#8]
问题如图
浏览器效果 ：
![image](https://user-images.githubusercontent.com/12181423/51757430-4a30b980-20fe-11e9-8ea4-253a0526aa97.png)

手机效果：
![image](https://user-images.githubusercontent.com/12181423/51757599-c4613e00-20fe-11e9-9fa2-7c15ec4fa90b.png)

代码如下

`
<div className={styles.result} ref={mainDom}>
     ...
</div>

private handleCreate = () => {
    const {
      mainDom: { current: mainDom },
    } = this.state;
    if (mainDom === null) {
      return;
    }
    let isCreacting = true;
    mainDom.style.display = 'block';
    // @ts-ignore
    import('@/utils/html2canvas.min.js')
      .then(({ default: html2canvas }) =>
        html2canvas(mainDom, {
          allowTaint: true, 
          tainttest: true,
          height: mainDom.clientHeight,
          width: mainDom.clientWidth,
          backgroundColor: '#00263c',
          scale: 2,
          letterRendering: true,
          logging: true,
        }),
      )
      .then(canvas => {
        setTimeout(() => {
          if (isCreacting) {
            isCreacting = false;
            alert('您的手机版本过低，请升级至最新版本后重新打开。');
          }
        }, 2000);
        const resultSrc = canvas.toDataURL('image/png');
        this.setState({ resultSrc }, () => {
          mainDom.style.display = 'none';
          isCreacting = false;
        });
      });
  };

// less 

.result {
  width: 100%;
  height: 100vh;
  background: #00263c;
  display: flex;
  flex-direction: column;
  font-variant: normal;
}

`

**Comment by hqwlkj** [comment]
已经处理 ，将 `font-variant: normal;` 修改为：`font-variant: small-caps;`  #https://github.com/niklasvh/html2canvas/pull/1706

**Comment by niuzhaoxia** [comment]
`font-variant: normal;` or `font-variant: small-caps;` 都不起作用

**Comment by Wendingchuan** [comment]
哈喽，请问遇到过在safari 中font-variant: normal; or font-variant: small-caps; 都不起作用的情况吗？
怎么处理呢
